### ISSUE TITLE
Is it possible to develop 1.10.2 version.

### ISSUE THREAD

**Issue by thtTNT** [is3000nx/SlashbladeAddOnPack#1]
I want run this add-on on a sponge server. Version 1.10.2 is stable in sponge. And lots of mod is update to 1.10.2. So I want to ask if it possible develop this add-on mod in 1.10.2 version. Sorry for my poor english. Thank you.

**Comment by is3000nx** [comment]
Please wait until the weekend.

**Comment by is3000nx** [comment]
Release for 1.10.2.

But,
I tested the creative mode(single) only.

Thank you.
